version: '3'
services:
    nuxt:
        restart: unless-stopped
        build:
            context: .
        volumes:
            - ./:/home/nuxt/
        network_mode: host
        ports:
            - '3000:3000'
        env_file:
            - .env
        command: ['npm', 'run', 'dev']
